### ISSUE TITLE
Zmiana typu w kontrolerze

### ISSUE THREAD

**Issue by ProfSJonalista** [ProfSJonalista/DoCeluNaCzas#29]
W MainPageFormController, w MainFormSearchRoute zmienić typ atrybutu "Time" z TimeSpan na DateTime
![image](https://user-images.githubusercontent.com/17982675/58368322-af00f280-7eeb-11e9-942c-974d6be1f705.png)

**Comment by Sinnlos** [comment]
![image](https://user-images.githubusercontent.com/18005044/58372823-990f2400-7f23-11e9-8886-cfe4e451281a.png)

**Comment by Sinnlos** [comment]
![image](https://user-images.githubusercontent.com/18005044/58372826-b47a2f00-7f23-11e9-8afe-bd949e3da93e.png)
